version: "3.4"
services:
  nginx:
  arc:
    container_name: arc
    image: arc
    restart: always
    command: --env="/arc-data/.env"
    depends_on:
      - "watcher"
    volumes:
      - "arc-data:/arc-data"
    ports:
      - 8000:8000
  nginx:
    container_name: arc_nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./nginx/error.html:/etc/nginx/html/50x.html
    ports:
      - 80:80
      - 443:443
  arc_configure:
    container_name: arc_configure
    image: appbaseio/arc-config:0.1.1
    restart: always
    depends_on:
      - "watcher"
    volumes:
      - "arc-data:/arc-data"
    ports:
      - 8080:8080
  watcher:
    build: ./watcher
    container_name: arc_watcher
    volumes:
      - "arc-data:/arc-data"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  arc-data:
    external: false
    name: arc-data
