version: "3.4"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
      - network.publish_host=_local_
      - network.host=_local_,_site_
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
    user: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  arc:
    container_name: arc
    image: appbaseio/arc:7.29.0
    restart: always
    command: --env="/arc-data/.env"
    depends_on:
      - "arc_configure"
    volumes:
      - "arc-data:/arc-data"
    ports:
      - 8000:8000
  nginx:
    container_name: arc_nginx
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs/
      - ./nginx/error.html:/etc/nginx/html/50x.html
      - "www:/var/www/html"
    ports:
      - 80:80
      - 443:443
    links:
      - arc_configure
  fluentbit:
    image: fluent/fluent-bit:1.0.4
    user: root
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - "arc"
      - "arc_configure"
    restart: always
    volumes:
      - "./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
      - "./parser.conf:/fluent-bit/etc/parser.conf"
      - "arc-data:/arc-data"
  arc_configure:
    container_name: arc_configure
    image: appbaseio/arc-config:0.2.3
    restart: always
    volumes:
      - "arc-data:/arc-data"
      - "www:/var/www/html"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  arc-data:
    external: false
    name: arc-data
  www:
    external: false
    name: www
